[package]
name = "revng-inkwell"
version = "0.1.0"
edition = "2024"
description = "Inkwell adaptors for borrowing and transforming revng-owned LLVM modules"
license = "MIT"
publish = false
include = ["/build.rs", "/src"]

[dependencies]
inkwell = { version = "0.9", default-features = false, features = ["llvm16-0-no-llvm-linking"] }
revng-sys = { version = "0.1", path = "../revng-sys" }
